import { test } from '@playwright/test';
import musicTests from './(search)/music';
import imagesTests from './(search)/images';
import newsTests from './(search)/news';
import shoppingTests from './(search)/shopping';
import videoTests from './(search)/video';
import webTests from './(search)/web';
import pagesTests from './(pages)';
import componentsTests from './(components)';
import mobileTests from './(mobile)';
import localeTests from './[locale]';

test.describe(musicTests);
test.describe(imagesTests);
test.describe(newsTests);
test.describe(pagesTests);
test.describe(componentsTests );
test.describe(shoppingTests);
test.describe(videoTests);
test.describe(webTests);
test.describe(mobileTests);
test.describe(localeTests);