name: Playwright Tests

on:
  schedule:
    - cron: '0 12 * * 5'
  pull_request:
    branches: [ main, master ]

jobs:
  playwright:
    name: 'Playwright Tests'
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.49.0-jammy

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
           node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install chrome browser
        run: npx playwright install chrome

      - name: Run UI tests
        run: npm run test:ui
        env:
          HOME: /root

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-ui-${{ github.run_id }}
          path: playwright-report/
          retention-days: 1

      - name: Run API tests
        run: npm run test:api
        if: always()
        env:
          HOME: /root

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-api-${{ github.run_id }}
          path: playwright-report/
          retention-days: 1
