name: Playwright Tests

on:
  pull_request:
    branches: [main, master]

jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Microsoft Edge browser
        run: npx playwright install msedge

      - name: Run tests
        run: |
          export QASE_REPORT=1
          export QASE_RUN_NAME=UI
          xvfb-run npx playwright test --project chromium firefox edge mobile &&
          export QASE_REPORT=2
          export QASE_RUN_NAME=API
          npx playwright test api
