name: Playwright Tests
on:
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    name: 'Playwright Tests'
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.40.0-jammy
    strategy:
      fail-fast: false
      matrix:
        project: [chromium, firefox,edge, mobile]
        shardIndex: [1]
        shardTotal: [1]    
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install chrome browser
        run: npx playwright install chrome
      - name: Run your tests
        run: npm run test
        env:
          HOME: /root
        

      
      



